version: "3.8"

services:
  redis:
    profiles:
      - single
      - cluster
      - base
    image: redis
    ports:
      - 6379:6379
    networks:
      - net

  rabbitmq:
    profiles:
      - single
      - cluster
      - base
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - net

  node1:
    profiles:
      - single
      - cluster
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - net
    depends_on:
      - redis
      - rabbitmq

  node2:
    profiles:
      - cluster
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - net
    depends_on:
      - redis
      - rabbitmq

networks:
  net: